/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.airlinereservationsystem.view;

/**
 *
 * @author Kerlly Chiriboga, ODS
 */
public class FrmAirlineReservation extends javax.swing.JFrame {

    /**
     * Creates new form FrmAirlineReservationSystem
     */
    public FrmAirlineReservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCustomer = new javax.swing.JMenu();
        itemUser = new javax.swing.JMenuItem();
        itemLogout = new javax.swing.JMenuItem();
        itemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemCreateCustomer = new javax.swing.JMenuItem();
        itemCreateFlight = new javax.swing.JMenu();
        itemFlight = new javax.swing.JMenuItem();
        mnuTicket = new javax.swing.JMenu();
        mnuOffer = new javax.swing.JMenu();
        mnuBaggage = new javax.swing.JMenu();
        itemQuestions = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuCustomer.setText("Airline Reservation");

        itemUser.setText("Crear Usuario");
        itemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUserActionPerformed(evt);
            }
        });
        mnuCustomer.add(itemUser);

        itemLogout.setText("Logout");
        mnuCustomer.add(itemLogout);

        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        mnuCustomer.add(itemExit);

        jMenuBar1.add(mnuCustomer);

        jMenu2.setText("Cliente");

        itemCreateCustomer.setText("Crear Cliente");
        itemCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreateCustomerActionPerformed(evt);
            }
        });
        jMenu2.add(itemCreateCustomer);

        jMenuBar1.add(jMenu2);

        itemCreateFlight.setText("Vuelo");

        itemFlight.setText("Crear Vuelo");
        itemFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFlightActionPerformed(evt);
            }
        });
        itemCreateFlight.add(itemFlight);

        jMenuBar1.add(itemCreateFlight);

        mnuTicket.setText("Ticket");
        jMenuBar1.add(mnuTicket);

        mnuOffer.setText("Ofertas");
        jMenuBar1.add(mnuOffer);

        mnuBaggage.setText("Equipaje");
        jMenuBar1.add(mnuBaggage);

        itemQuestions.setText("Ayuda");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Preguntas comunes");
        itemQuestions.add(jCheckBoxMenuItem2);

        jMenuBar1.add(itemQuestions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreateCustomerActionPerformed
        FrmCreateCustomer frmCreateCustomer = new FrmCreateCustomer();
        this.setVisible(false);
        frmCreateCustomer.setVisible(true);
  
    }//GEN-LAST:event_itemCreateCustomerActionPerformed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemUserActionPerformed

    private void itemFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFlightActionPerformed
       FrmCreateFlight frmCreateFlight = new FrmCreateFlight();
       this.setVisible(false);
       frmCreateFlight.setVisible(true);
    }//GEN-LAST:event_itemFlightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAirlineReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAirlineReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAirlineReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAirlineReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAirlineReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCreateCustomer;
    private javax.swing.JMenu itemCreateFlight;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemFlight;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JMenu itemQuestions;
    private javax.swing.JMenuItem itemUser;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mnuBaggage;
    private javax.swing.JMenu mnuCustomer;
    private javax.swing.JMenu mnuOffer;
    private javax.swing.JMenu mnuTicket;
    // End of variables declaration//GEN-END:variables
}
