/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ec.espe.edu.AirlineReservationSystem.view;

import static com.mongodb.client.model.Filters.type;
import ec.espe.edu.AirlineReservationSystem.controller.BaggageController;
import ec.espe.edu.AirlineReservationSystem.controller.TicketController;
import ec.espe.edu.AirlineReservationSystem.model.Baggage;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Joffre
 */
public class WeigthBaggagePanel extends javax.swing.JPanel {
private String baggageType;
    /**
     * Creates new form WeigthBaggagePanel
     */
    public WeigthBaggagePanel(String baggageType) {
        
 this.baggageType = baggageType;
 
        initComponents();
        
        
    }

    
      
        
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        arstxt = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ConfirmBton = new javax.swing.JButton();
        weigth = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setRequestFocusEnabled(false);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        arstxt.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        arstxt.setForeground(new java.awt.Color(255, 255, 255));
        arstxt.setText("Airline Reservation System");
        background.add(arstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 300, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/airlinereservationsystem/images/fondo.jpeg"))); // NOI18N
        background.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 48));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/airlinereservationsystem/images/equipaje-de-viaje.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 140, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/airlinereservationsystem/images/airline company icon .jpg"))); // NOI18N
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 150, 140));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setText("Ingrese el peso del equipaje:");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, 20));

        jLabel4.setText("(C) Overnight Developerr Squad - ODS");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jLabel5.setText("(R) Overnight Developer Squad");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        ConfirmBton.setText("Confirmar");
        ConfirmBton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtonActionPerformed(evt);
            }
        });
        background.add(ConfirmBton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 90, -1));

        weigth.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        weigth.setMajorTickSpacing(10);
        weigth.setMaximum(30);
        weigth.setMinorTickSpacing(1);
        weigth.setPaintLabels(true);
        weigth.setPaintTicks(true);
        weigth.setSnapToTicks(true);
        weigth.setToolTipText("");
        background.add(weigth, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setText("Kilogramos");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("Señor Usuario recuerde que solo puede");
        background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 290, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setText("incluir dos maletas en su viaje...");
        background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmBtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtonActionPerformed
  try {
        int weightValue = weigth.getValue();
           
        if (weightValue <= 0) {
            JOptionPane.showMessageDialog(this, "El peso debe ser mayor que 0.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
      
         int ticketId = BaggageController.getTicketId();
            TicketController ticketController = new TicketController();
            ticketController.updateTicketWithBaggage(ticketId, baggageType, weightValue);
        
        JOptionPane.showMessageDialog(this, "Peso confirmado: " + weightValue + " kilogramos", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        
        
        JOptionPane.showMessageDialog(this, "El equipaje se ha añadido a su Ticket!", "Confirmación", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        e.printStackTrace();
    }

        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_ConfirmBtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmBton;
    private javax.swing.JLabel arstxt;
    private javax.swing.JPanel background;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSlider weigth;
    // End of variables declaration//GEN-END:variables
}
