/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ec.espe.edu.AirlineReservationSystem.view;

import ec.espe.edu.AirlineReservationSystem.controller.BaggageController;
import ec.espe.edu.AirlineReservationSystem.controller.TicketController;
import ec.espe.edu.AirlineReservationSystem.view.BaggagePanel.ButtonManager;
import javax.swing.SwingUtilities;

/**
 *
 * @author Joffre
 */
public class IdTicket extends javax.swing.JPanel { 
    /**
     * Creates new form IdTicket
     */
    public IdTicket() {
        initComponents();
    }
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        arstxt = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        IdTickettxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ValidarBton = new javax.swing.JButton();
        Validaciontxt = new javax.swing.JLabel();

        setEnabled(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setRequestFocusEnabled(false);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        arstxt.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        arstxt.setForeground(new java.awt.Color(255, 255, 255));
        arstxt.setText("Airline Reservation System");
        background.add(arstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 300, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/airlinereservationsystem/images/fondo.jpeg"))); // NOI18N
        background.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 48));

        IdTickettxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTickettxtActionPerformed(evt);
            }
        });
        background.add(IdTickettxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/airlinereservationsystem/images/ticket.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 160, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/airlinereservationsystem/images/airline company icon .jpg"))); // NOI18N
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 150, 140));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setText("Ingrese el Ticket ID:");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setText("(C) Overnight Developerr Squad - ODS");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jLabel5.setText("(R) Overnight Developer Squad");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 90, -1));

        ValidarBton.setText("Validar");
        ValidarBton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidarBtonActionPerformed(evt);
            }
        });
        background.add(ValidarBton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        Validaciontxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        background.add(Validaciontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 300, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IdTickettxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTickettxtActionPerformed

    }//GEN-LAST:event_IdTickettxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try {
    String ticketIdText = IdTickettxt.getText().trim();
    if (ticketIdText.isEmpty()) {
        Validaciontxt.setText("ID del ticket no puede estar vacío.");
        ButtonManager.enableButtons(false);
        return;
    }
    if (!ticketIdText.matches("\\d+")) {
        Validaciontxt.setText("ID del ticket no válido. Debe ser un número.");
        ButtonManager.enableButtons(false);
        return;
    }
    int ticketId = Integer.parseInt(ticketIdText);

    TicketController ticketController = new TicketController();
    String result = ticketController.findTicketById(ticketId);
    Validaciontxt.setText(result);

    if (result.contains("Cliente Encontrado")) {
        BaggageController.setTicketId(ticketId);
        ButtonManager.enableButtons(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    } else {
        ButtonManager.enableButtons(false);
    }
} catch (Exception e) {
    Validaciontxt.setText("Ocurrió un error inesperado.");
    e.printStackTrace();
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ValidarBtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidarBtonActionPerformed
String ticketIdStr = IdTickettxt.getText().trim();
    if (!ticketIdStr.matches("\\d+")) {
        Validaciontxt.setText("ID del ticket no válido. Debe ser un número.");
        return;
    }

    int ticketId = Integer.parseInt(ticketIdStr);

 
    TicketController ticketController = new TicketController();

   
 String ticket = ticketController.findTicketById(ticketId);
    
    Validaciontxt.setText(ticket);

    }//GEN-LAST:event_ValidarBtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdTickettxt;
    private javax.swing.JLabel Validaciontxt;
    private javax.swing.JButton ValidarBton;
    private javax.swing.JLabel arstxt;
    private javax.swing.JPanel background;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel exitBtn1;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel exitTxt1;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
